spring:
  application:
    name: ecommerce
  messages:
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: softeni0926
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      continue-on-error: true
  cache:
    type: simple

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.example.domain.model.enums.GenericEnumTypeHandler

#設定値
registration:
  expiration-time-minutes: 10

