spring:
  application:
    name: ecommerce
  messages:
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: softeni0926
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      continue-on-error: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
