package com.example.domain.mapper;

import com.example.domain.model.entity.Prefecture;
import com.example.domain.model.entity.PrefectureExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PrefectureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture
     *
     * @mbg.generated
     */
    long countByExample(PrefectureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture
     *
     * @mbg.generated
     */
    int deleteByExample(PrefectureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String prefectureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture
     *
     * @mbg.generated
     */
    int insert(Prefecture row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture
     *
     * @mbg.generated
     */
    int insertSelective(Prefecture row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture
     *
     * @mbg.generated
     */
    List<Prefecture> selectByExample(PrefectureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture
     *
     * @mbg.generated
     */
    Prefecture selectByPrimaryKey(String prefectureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Prefecture row, @Param("example") PrefectureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Prefecture row, @Param("example") PrefectureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Prefecture row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Prefecture row);
}