package com.example.domain.model.entity;

import java.time.LocalDateTime;

public class Prefecture {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefecture.prefecture_id
     *
     * @mbg.generated
     */
    private String prefectureId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefecture.prefecture_name
     *
     * @mbg.generated
     */
    private String prefectureName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefecture.display_order
     *
     * @mbg.generated
     */
    private Integer displayOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefecture.created_at
     *
     * @mbg.generated
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefecture.updated_at
     *
     * @mbg.generated
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefecture.prefecture_id
     *
     * @return the value of prefecture.prefecture_id
     *
     * @mbg.generated
     */
    public String getPrefectureId() {
        return prefectureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefecture.prefecture_id
     *
     * @param prefectureId the value for prefecture.prefecture_id
     *
     * @mbg.generated
     */
    public void setPrefectureId(String prefectureId) {
        this.prefectureId = prefectureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefecture.prefecture_name
     *
     * @return the value of prefecture.prefecture_name
     *
     * @mbg.generated
     */
    public String getPrefectureName() {
        return prefectureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefecture.prefecture_name
     *
     * @param prefectureName the value for prefecture.prefecture_name
     *
     * @mbg.generated
     */
    public void setPrefectureName(String prefectureName) {
        this.prefectureName = prefectureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefecture.display_order
     *
     * @return the value of prefecture.display_order
     *
     * @mbg.generated
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefecture.display_order
     *
     * @param displayOrder the value for prefecture.display_order
     *
     * @mbg.generated
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefecture.created_at
     *
     * @return the value of prefecture.created_at
     *
     * @mbg.generated
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefecture.created_at
     *
     * @param createdAt the value for prefecture.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefecture.updated_at
     *
     * @return the value of prefecture.updated_at
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefecture.updated_at
     *
     * @param updatedAt the value for prefecture.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}