package com.example.domain.model.entity;

import java.time.LocalDate;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_id
     *
     * @mbg.generated
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbg.generated
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_description
     *
     * @mbg.generated
     */
    private String productDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.stock
     *
     * @mbg.generated
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.category_id
     *
     * @mbg.generated
     */
    private String categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.start_sale_date
     *
     * @mbg.generated
     */
    private LocalDate startSaleDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.end_sale_date
     *
     * @mbg.generated
     */
    private LocalDate endSaleDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_id
     *
     * @return the value of product.product_id
     *
     * @mbg.generated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_id
     *
     * @param productId the value for product.product_id
     *
     * @mbg.generated
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_name
     *
     * @return the value of product.product_name
     *
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_name
     *
     * @param productName the value for product.product_name
     *
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbg.generated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbg.generated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_description
     *
     * @return the value of product.product_description
     *
     * @mbg.generated
     */
    public String getProductDescription() {
        return productDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_description
     *
     * @param productDescription the value for product.product_description
     *
     * @mbg.generated
     */
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.stock
     *
     * @return the value of product.stock
     *
     * @mbg.generated
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.stock
     *
     * @param stock the value for product.stock
     *
     * @mbg.generated
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.category_id
     *
     * @return the value of product.category_id
     *
     * @mbg.generated
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.category_id
     *
     * @param categoryId the value for product.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.start_sale_date
     *
     * @return the value of product.start_sale_date
     *
     * @mbg.generated
     */
    public LocalDate getStartSaleDate() {
        return startSaleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.start_sale_date
     *
     * @param startSaleDate the value for product.start_sale_date
     *
     * @mbg.generated
     */
    public void setStartSaleDate(LocalDate startSaleDate) {
        this.startSaleDate = startSaleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.end_sale_date
     *
     * @return the value of product.end_sale_date
     *
     * @mbg.generated
     */
    public LocalDate getEndSaleDate() {
        return endSaleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.end_sale_date
     *
     * @param endSaleDate the value for product.end_sale_date
     *
     * @mbg.generated
     */
    public void setEndSaleDate(LocalDate endSaleDate) {
        this.endSaleDate = endSaleDate;
    }
}