package com.example.domain.model.entity;

public class Review extends ReviewKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.rating
     *
     * @mbg.generated
     */
    private Integer rating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.review_text
     *
     * @mbg.generated
     */
    private String reviewText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.rating
     *
     * @return the value of review.rating
     *
     * @mbg.generated
     */
    public Integer getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.rating
     *
     * @param rating the value for review.rating
     *
     * @mbg.generated
     */
    public void setRating(Integer rating) {
        this.rating = rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.review_text
     *
     * @return the value of review.review_text
     *
     * @mbg.generated
     */
    public String getReviewText() {
        return reviewText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.review_text
     *
     * @param reviewText the value for review.review_text
     *
     * @mbg.generated
     */
    public void setReviewText(String reviewText) {
        this.reviewText = reviewText;
    }
}