package com.example.domain.model.entity;

import java.time.LocalDate;
import java.time.LocalDateTime;

import com.example.domain.model.enums.Gender;
import com.example.domain.model.enums.UserRole;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.first_name_kanji
     *
     * @mbg.generated
     */
    private String firstNameKanji;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_name_kanji
     *
     * @mbg.generated
     */
    private String lastNameKanji;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.first_name_kana
     *
     * @mbg.generated
     */
    private String firstNameKana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_name_kana
     *
     * @mbg.generated
     */
    private String lastNameKana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gender
     *
     * @mbg.generated
     */
    private Gender gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birth_date
     *
     * @mbg.generated
     */
    private LocalDate birthDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.post_code
     *
     * @mbg.generated
     */
    private String postCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.prefecture_id
     *
     * @mbg.generated
     */
    private String prefectureId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.address1
     *
     * @mbg.generated
     */
    private String address1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.address2
     *
     * @mbg.generated
     */
    private String address2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone_number
     *
     * @mbg.generated
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.role
     *
     * @mbg.generated
     */
    private UserRole role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.created_at
     *
     * @mbg.generated
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.updated_at
     *
     * @mbg.generated
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.first_name_kanji
     *
     * @return the value of user.first_name_kanji
     *
     * @mbg.generated
     */
    public String getFirstNameKanji() {
        return firstNameKanji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.first_name_kanji
     *
     * @param firstNameKanji the value for user.first_name_kanji
     *
     * @mbg.generated
     */
    public void setFirstNameKanji(String firstNameKanji) {
        this.firstNameKanji = firstNameKanji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.last_name_kanji
     *
     * @return the value of user.last_name_kanji
     *
     * @mbg.generated
     */
    public String getLastNameKanji() {
        return lastNameKanji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.last_name_kanji
     *
     * @param lastNameKanji the value for user.last_name_kanji
     *
     * @mbg.generated
     */
    public void setLastNameKanji(String lastNameKanji) {
        this.lastNameKanji = lastNameKanji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.first_name_kana
     *
     * @return the value of user.first_name_kana
     *
     * @mbg.generated
     */
    public String getFirstNameKana() {
        return firstNameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.first_name_kana
     *
     * @param firstNameKana the value for user.first_name_kana
     *
     * @mbg.generated
     */
    public void setFirstNameKana(String firstNameKana) {
        this.firstNameKana = firstNameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.last_name_kana
     *
     * @return the value of user.last_name_kana
     *
     * @mbg.generated
     */
    public String getLastNameKana() {
        return lastNameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.last_name_kana
     *
     * @param lastNameKana the value for user.last_name_kana
     *
     * @mbg.generated
     */
    public void setLastNameKana(String lastNameKana) {
        this.lastNameKana = lastNameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gender
     *
     * @return the value of user.gender
     *
     * @mbg.generated
     */
    public Gender getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gender
     *
     * @param gender the value for user.gender
     *
     * @mbg.generated
     */
    public void setGender(Gender gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birth_date
     *
     * @return the value of user.birth_date
     *
     * @mbg.generated
     */
    public LocalDate getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birth_date
     *
     * @param birthDate the value for user.birth_date
     *
     * @mbg.generated
     */
    public void setBirthDate(LocalDate birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.post_code
     *
     * @return the value of user.post_code
     *
     * @mbg.generated
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.post_code
     *
     * @param postCode the value for user.post_code
     *
     * @mbg.generated
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.prefecture_id
     *
     * @return the value of user.prefecture_id
     *
     * @mbg.generated
     */
    public String getPrefectureId() {
        return prefectureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.prefecture_id
     *
     * @param prefectureId the value for user.prefecture_id
     *
     * @mbg.generated
     */
    public void setPrefectureId(String prefectureId) {
        this.prefectureId = prefectureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.address1
     *
     * @return the value of user.address1
     *
     * @mbg.generated
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.address1
     *
     * @param address1 the value for user.address1
     *
     * @mbg.generated
     */
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.address2
     *
     * @return the value of user.address2
     *
     * @mbg.generated
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.address2
     *
     * @param address2 the value for user.address2
     *
     * @mbg.generated
     */
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone_number
     *
     * @return the value of user.phone_number
     *
     * @mbg.generated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone_number
     *
     * @param phoneNumber the value for user.phone_number
     *
     * @mbg.generated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.role
     *
     * @return the value of user.role
     *
     * @mbg.generated
     */
    public UserRole getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.role
     *
     * @param role the value for user.role
     *
     * @mbg.generated
     */
    public void setRole(UserRole role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.created_at
     *
     * @return the value of user.created_at
     *
     * @mbg.generated
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.created_at
     *
     * @param createdAt the value for user.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.updated_at
     *
     * @return the value of user.updated_at
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.updated_at
     *
     * @param updatedAt the value for user.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}